### ISSUE TITLE
Minor Bug: Making a comment deletes a post

### ISSUE THREAD

**Issue by hannanajmal** [info442-spr22/b-team#102]
I do not know if  someone was testing something but, after I commented on one of my posts, it was then deleted.
Expected: being able to view a comment on the post
Actual: post was then deleted 
Google Chrome Version 101.0.4951.67 (Official Build) (64-bit) Windows 10

**Comment by jeannechoi00** [comment]
- Seems to be working on our end. Users posts are not deleted when commenting on post
