### ISSUE TITLE
[Enhancement] Consider putting reviewing posts in a separate page

### ISSUE THREAD

**Issue by MARY4177** [info442-spr22/b-team#104]
Putting reviewing posts on a separate page would make users easily understand the website because I personally thought clicking the home button did not work because I thought I was on a different page.

● optional attachments (screenshots, error logs, etc)
<img width="490" alt="스크린샷 2022-05-18 오전 10 05 23" src="https://user-images.githubusercontent.com/55933930/169101064-76d2ce6a-7343-4062-84e2-5dd7a80352e5.png">

**Comment by jeannechoi00** [comment]
- Will highlight what tab they are on in the nav bar

**Comment by soshikun** [comment]
- Tab links are green when they are focused to show the current page
