### ISSUE TITLE
Minor bug: Can comment with no content

### ISSUE THREAD

**Issue by sharlenef** [info442-spr22/b-team#106]
Clicking on the comment input and hitting submit will trigger a sign telling users to fill out the form. But after hitting the "back" button and going back into the post, a empty comment will appear

Tested on: Chrome Version 101.0.4951.54 on macOS Big Sur

Steps to reproduce:

1. Create a post with any content and post it
2. After it's posted, go to home to click into post by clicking "more info"
3. Click into the comment form (don't type anything)
4. Click 'Comment"
5. Click 'Back' to go back to home
6. Go back into the post you made by clicking 'more info'
7. There will be an empty comment down below the post

Expected result: no empty comments appear, users can't post comment with nothing in it

Actual result: empty comments appear, users can post comment with nothing

<img width="659" alt="Screen Shot 2022-05-18 at 2 27 09 PM" src="https://user-images.githubusercontent.com/70997571/169158663-0336de76-2909-4cff-ad0a-ccd80ef1ab3d.png">

**Comment by jeannechoi00** [comment]
- Will be completing in "More Info" page

**Comment by soshikun** [comment]
- [ ] Try to reproduce bug
- [ ] Double check conditional statement for empty comments
- [ ] Fix the empty comments refreshing bug
