### ISSUE TITLE
Forum Component

### ISSUE THREAD

**Issue by jeannechoi00** [info442-spr22/b-team#15]
The following will included to complete the forum page components:
- [x] The Forum Component will be displayed in the `/home` route
- [x] The Better Educators logo will be at the top of the page
- [x] posts will be in chronological order
- [x] Scrolling is allowed through the forum posts
- [x] Displays all posts from database in the middle of the page
- [x] Post will be in individual containers
- [x] Post will have `title, text, and author` displayed

**Comment by victorgmaciel** [comment]
Forum component on the home page is complete. No issues.
