### ISSUE TITLE
Feature: Rental Sign-Up

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/b-team#4]
**Implement page for individual rentals and sign-up for the rental**

- [ ] Format text description and image for the rental using HTML and CSS.
- [ ] Add navigation bar, site logo, and site title to their respective locations using HTML and CSS.
- [ ] Create the form to sign-up for the specific rental with input fields for email, name, and phone number.
- [ ] In the case of a missing form input, create error message that will be displayed next to the field with a missing input.
- [ ] Store user inputs to database (firebase) using JS.
- [ ] Create a confirmation pop-up that will be shown after the user submits the form using JS, HTML, and CSS.
- [ ] Ensure forms are properly functioning
- [ ] Close issue

**Comment by jeannechoi00** [comment]
Closing issue since it was a lab assignment
