### ISSUE TITLE
Feature: Filtering System

### ISSUE THREAD

**Issue by soshikun** [info442-spr22/b-team#5]
**Implement filtering system**

- [ ] 1. Create sidebar for filters on rental page using HTML and CSS
- [ ] 2. Create filter form using HTML and CSS
- [ ] 3. Create the location, type of technology, and distance filters using HTML and CSS
- [ ] 4. Add functionality via JavaScript including error handling 
- [ ] 5. In the case of an error, create error message display using HTML, CSS, and JavaScript
- [ ] 6. Ensure forms are working with no bugs
- [ ] 7. Close issue

**Comment by jeannechoi00** [comment]
Closing issue since it was a lab assignment
