### ISSUE TITLE
Report Pop up

### ISSUE THREAD

**Issue by jeannechoi00** [info442-spr22/b-team#59]
The following will be what will happen when the report button is clicked:

Once a user clicks the report button a pop-up with the following will be shown on screen
- [x] Short instruction description at the top of the pop-up
- [x] check-boxes/radio buttons to select the type issue the resource is being faced with. Issues include:
- [x] Invalid link
- [x] Inappropriate link/content
- [x] Fraud

- [x] Below check-boxes are text boxes for the users name, school, resource, description detail (to allow users to describe in further detail), and preferred form of contact
- [x] Below text input box is the submit button at the bottom

**Comment by victorgmaciel** [comment]
Completed form structure.
