### ISSUE TITLE
Feature: Interactive Map (Stretch)

### ISSUE THREAD

**Issue by victorgmaciel** [info442-spr22/b-team#6]
**Implement Interactive Map**

- [ ] 1. Find SVG of Washington State
- [ ] 2. Import SVG and display it on landing/home page
- [ ] 3. Code necessary CSS,HTML to position map in middle of website
- [ ] 4. Create interactive portion(Hover via CSS, eventListener via JS, etc)
- [ ] 5. Ensure proper functionality 
- [ ] 6. Close Issue

**Comment by jeannechoi00** [comment]
Closing issue since it was a lab assignment
