### ISSUE TITLE
(Minor) The "Submit" does not say whether form as been submitted

### ISSUE THREAD

**Issue by hannanajmal** [info442-spr22/b-team#80]
The submit button after filling out the form is not giving an indication that the post has been submitted. 
Expected result: there is supposed to be a page that says the form as been submitted
actual result: screen does not change and submit button does not respond after clicking on it 

Google Chrome Version 101.0.4951.67 (Official Build) (64-bit) Windows 10

**Comment by jeannechoi00** [comment]
- Currently have "Thank you for submitting" add "Now returning to home page insert emoji" (make more visually appealing, make text larger)
- Make timer for changing page longer

**Comment by jeannechoi00** [comment]
- report form

**Comment by victorgmaciel** [comment]
Fixed bug, report form now shows div for `4` seconds before closing.
Added some style for visual effect.
