### ISSUE TITLE
[Major Bug]: Can delete other user's comments

### ISSUE THREAD

**Issue by cavazd** [info442-spr22/b-team#81]
**Major bug**

* Summary: After signing in, I could delete comments from other users.
* Environment: Firefox 100.0.1 on Windows11
* Steps to reproduce: Sign in, click on someone else's comment, click delete, confirm delete (sorry for deleting one of your comments)
* Expected result: Not seeing a delete button if the comment isn't mine
* Actual result: Seeing a delete button and being able to delete someone else's comment/post

**Comment by cherimarie** [comment]
I agree that this is a major bug. Both posts and comments can be deleted.

**Comment by kasayachith** [comment]
We will fix this by trying to figure out how to make the delete button only available on posts made by the user

**Comment by soshikun** [comment]
- [ ] Create conditional statement to check that the post's author ID is equal to the current user's ID
- [ ] Use conditional statement to display the Delete button if applicable
