### ISSUE TITLE
(Minor) Can also delete other users' posts

### ISSUE THREAD

**Issue by soopark82** [info442-spr22/b-team#83]
Confused why the authentication exists and if anyone can delete anyone's posts.

Severity: minor
Environment: Chrome v101.0.4951.67 on Windows
expected result: the button to delete other users' posts disabled
actual result: the button to delete other users' posts abled

**Comment by kasayachith** [comment]
Same issue as #81, but a different solution. We will be considering this expected result when we are deciding which solution we want to choose to fix the issue.
