### ISSUE TITLE
Enhancement: Make button selectable also when not clicking on the text in the button

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/b-team#87]
When clicking into more info about a post, the "back" button can only be responsive if I click on the word. Clicking on areas inside the button would not work. It would be better because the it would make it faster and smoother for users to navigate

**Comment by victorgmaciel** [comment]
- [ ] Fix `a` css in order to be clickable all over 
- [ ] ensure proper media sizing for various screens

**Comment by victorgmaciel** [comment]
completed
