### ISSUE TITLE
Enhancement: Cluttered Nav bar content

### ISSUE THREAD

**Issue by GuillyGuillaume** [info442-spr22/b-team#88]
Buttons and Text in the navbar could be better separated.
The logo placed side by side with nav links makes it appear odd and cluttered.
Possible improvements:
 - Move logo off to a side on it's own.
 - Link buttons change color when hovered.
 - Match font/style of login and logout buttons.
 - Add more spacing between buttons.

**Comment by jeannechoi00** [comment]
- Will be implementing this nav bar change along with issue #104 to create a clear sense of the nav bar. Thanks for the enhancement!

**Comment by soshikun** [comment]
- Moved logo to the left of the screen for all screen sizes
- Navigation links change color when hovered and when they are clicked
