### ISSUE TITLE
Feature: Rental System 

### ISSUE THREAD

**Issue by avaghela-1925502** [info442-spr22/b-team#9]
**Implement page displaying all rentals**

- [ ] Format filters, rental previews, and search bar in respective areas as shown in the design specification using HTML and CSS
- [ ] Add navigation bar, site logo, and site title to their respective locations using HTML and CSS.
- [ ] Create cards displaying each rental that can be clicked to redirect the user to a page with full details using HTML, CSS, and JS.
- [ ] Align the cards to fit the page and ensure that the user can scroll through them.
- [ ] In the case that no results are found based on what is typed into the search bar, create an error message displaying under the search bar "no results found" using JS.
- [ ] Close issue

**Comment by jeannechoi00** [comment]
Closing issue since it was a lab assignment
