### ISSUE TITLE
(Enhancement) Back to Top button

### ISSUE THREAD

**Issue by spudists** [info442-spr22/b-team#96]
When scrolling through all the comments, it would be nice to have a "return to top" button at the end of all the posts to avoid excessive scrolling

**Comment by jeannechoi00** [comment]
- Will be implementing this design update for this upcoming sprint. Thank you for the suggestion!

**Comment by soshikun** [comment]
- [ ] Create button div
- [ ] Add functionality to scroll the user to the top of the page again
