### ISSUE TITLE
(Minor Bug) Can submit a report without selecting the type of issue

### ISSUE THREAD

**Issue by stroz08** [info442-spr22/b-team#98]
Severity: minor
Summary: Users can submit reports without selecting the issue type
Environment: Chrome Version 101.0.4951.67, Windows 10
Steps to reproduce: Submit a report without selecting a type
Expected result: A notification saying you must select the type
Actual result: a submitted report
It would also be nice if you had an "other" field or a "custom" field where you can input what issue type it is.

**Comment by victorgmaciel** [comment]
- [ ] Make all radio buttons `required` in order for form to only submit if clicked. 
- [ ] Create an `other` option for users.

**Comment by victorgmaciel** [comment]
completed.
